system:
  embedding_model: "all-MiniLM-L6-v2"
  llm_model: "phi3:mini"
  chunk_size: 512
  chunk_overlap: 50

paths:
  index_path: "./indexes/"
  documents_path: "./literatur/"
  output_path: "./output/"

search:
  top_k: 5
  relevance_threshold: 0.7
  
performance:
  cpu_only: true
  max_memory_usage: 80
  ollama_batch_size: 4  # Batch size for Ollama requests
  cache_responses: true
  max_concurrent_requests: 8