system:
  embedding_model: "all-MiniLM-L6-v2"
  llm_model: "phi3:mini"
  chunk_size: 256
  chunk_overlap: 20

paths:
  index_path: "./indexes/"
  documents_path: "./literatur/"
  output_path: "./output/"

search:
  top_k: 5
  relevance_threshold: 0.7
  
performance:
  cpu_only: true
  max_memory_usage: 80